import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/custom-ui/Header";
import Footer from "@/components/custom-ui/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const poppins = Poppins({
//   variable: "--font-poppins",
//   subsets: ["latin"],
//   weight: ["400", "600"],
// });

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "KT Windows Pty Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className}  flex flex-col items-center w-full`}
      >
        <div
          className={`flex flex-col justify-between h-[100dvh] w-full max-w-[1200px] `}
        >
          <div className="flex flex-col gap-2">
            <Header />
            {children}
            <Toaster />
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
